---
- name: nginx installation, start and enable
  hosts: host1
  tasks:
    - name: Install nginx
      yum:
        name: epel-release
        state: latest
    - name: Install nginx
      yum:
        name: nginx
        state: latest
    - name: Ensure nginx is enabled
      systemd: 
        name: nginx
        state: started
        enabled: yes
