---
- name: 
  hosts: managed_hosts
  tasks:
    - name: Install nginx
      yum:
        name: ["nginx"]
        state: present
    - name: Ensure nginx is enabled
      service: 
        name: nginx
        state: started
