---
- name: Bootstrap server
  hosts: group1
  gather_facts: yes
  vars:
    packages: ["vim"]
    state: "present"
  tasks:
    - name: Install wim, wget, curl, tree for CentOS
      yum:
        name: "{{ packages }}"
        state: "{{ state }}"
      when:
        - ansible_pkg_mgr == "yum"
    - name: Install wim, wget, curl, tree for Ubuntu
      
      apt:
        name: "{{ packages }}"
        state: "{{ state }}"
      when:
        - ansible_pkg_mgr == "apt"
        - ansible_distribution == "Ubuntu"
  