---
- name: Update Packages, Install Packages, Create and Insert lines to a file
  hosts: localhost
  tasks:
    - name: Update all "yum" packages
      yum: 
        name: '*'
        state: latest
    - name: Install vim, tree, wget and curl
      yum:
        name: ["vim", "tree", "wget", "curl"]
        state: latest
    - name: Create an empty file
      file:
        path: /tmp/file1_ansible
        state: touch
    - name: Insert lines to a file
      blockinfile:
        path: /tmp/file1_ansible
        block: |
         this is line one
         this is line two