---
- name: Update Packages
  hosts: localhost
  tasks:
    - name: Update all packages
      yum: 
        name: '*'
        state: latest
    - name: Install vim, tree, wget and curl
      yum:
        name: ["vim", "tree", "wget", "curl"]
        state: latest
    - name: Create a file
      file:
        path: /tmp/file1_ansible
        state: touch
    - name: Add lines
      blockinfile:
        path: /tmp/file1_ansible
        block: |
         this is line one
         this is line two